version: '2'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    ports:
      - '127.0.0.1:5432:5432'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'

  mongo:
    container_name: 'mongo'
    image: 'mongo:3.3'
    command: '--storageEngine wiredTiger'
    ports:
      - '127.0.0.1:27017:27017'
